name: Build and Deploy to S3 with OIDC

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd frontend/app
          npm ci
          npm run build  # Reactアプリケーションのビルドコマンド

      - name: Assume AWS Role OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::122905384833:role/zumens-dev-githubactions-iam-role
          role-duration-seconds: 1200
          role-session-name: github-actions
          aws-region: ap-northeast-1  # 使用するリージョンに応じて変更してください
          mask-aws-account-id: false

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://myapp-dev-deploy-bucket-plo4pm
